version: '3'
services:
  worker:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    links:
    - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
